### ISSUE TITLE
How to install nix on Uberspace 7

### ISSUE THREAD

**Issue by tuxflo** [jorsn/ubernix#1]
Hi :wave: 

since the creation of the installation guide is still an open TODO I just want to ask on how to install nix on an uberspace 7 host?
I tried the nix-user-chroot rootless installation mentioned in the docs but this fails with 
```
thread 'main' panicked at 'unshare failed: Sys(EINVAL)', src/main.rs:124:70
```
which seems to be a known problem that is not solvable by non-root users.

**Comment by jorsn** [comment]
Unshare fails, because Uberspace does not enable the necessary Linux namespaces (user, mount, uts, if i remember correctly).

Therefore, a tool like proot is needed. Unfortunately, this does not work reliably, for long-running services (see https://github.com/Uberspace/lab/issues/525). Also, it impacts performance, because it lacks real threading.
The script `nix-init` in the `tools` directory, here, uses proot.

See also https://discourse.nixos.org/t/fakechroot-instead-of-proot-for-unprivileged-nix-installs/11551

**Comment by jorsn** [comment]
Since that seems so simple, maybe it makes more sense to set up a virtual nixos machine somewhere than to use nix on an Uberspace, if your usecase does not combine traditional Uberspace stuff and nix.

**Comment by tuxflo** [comment]
Thanks for the reply. My usecase was somewhat special: I needed to upgrade an old Nextcloud instance which did not support the Uberspace PHP versions anymore. So I needed to find a way to install PHP 7.4 temporary to install the Nextcloud upgrades. At first I tried to use brew/homebrew but installing PHP didn't work out of the box and also it took forever since it tried to compile it's own glibc and so on.
Then I found https://github.com/DavHau/nix-portable which has some built in workarounds (proot? bubblewrap?) for non root systems.

And that actually worked pretty good, at least for my usecase. But I don't know if it is even possible to run services with nix-portable, I just used a nix-shell to fix my issue.
